#!/usr/bin/env sh

limelight -m config width 3
limelight -m config radius 10
limelight -m config placement exterior
# limelight -m config active_color 0xFF40FF00
# limelight -m config normal_color 0x00FFFFFF
# limelight -m config normal_color 0xFF887191
limelight -m config active_color 0xFFD8DEE9
limelight -m config normal_color 0xFF81A1C1

echo "limelight configuration loaded.."
